version: "3"
services:
  islamapp:
    hostname: islamapp
    container_name: islamapp
    build: 
      context: ./
      dockerfile: ./islamapp/Dockerfile
    env_file:
      - ./config/${APP_ENV:-default}.env
    restart: always
  mysql-databse:
    build: ./database
    restart: always
    environment:
      MYSQL_PASSWORD: islam
      MYSQL_ROOT_PASSWORD: islam
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
  mongo-databse:
    build: ./mongo-database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: islam
      MONGO_INITDB_ROOT_PASSWORD: islam
    volumes:
      - ./mdb:/etc/mongo
    ports:
      - 27017:27017
