version: "3"
services:
  islamapp:
    hostname: islamapp
    container_name: islamapp
    build: 
      context: ./
      dockerfile: ./islamapp/Dockerfile
    env_file:
      - ./config/${APP_ENV:-default}.env
    depends_on:
      - mongo-databse
      - mysql-databse
    restart: always
    ports:
      - 5555:5555
  mysql-databse:
    hostname: mysql-databse
    container_name: mysql-databse
    build: ./database
    restart: always
    environment:
      MYSQL_PASSWORD: islam
      MYSQL_ROOT_PASSWORD: islam
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
  mongo-databse:
    hostname: mongo-databse
    container_name: mongo-databse
    build: ./mongo-database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: islam
      MONGO_INITDB_ROOT_PASSWORD: islam
    volumes:
      - ./mdb:/etc/mongo
    ports:
      - 27017:27017
