version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
