name: CI - Linter

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f islamapp/requirements.txt ]; then pip install -r islamapp/requirements.txt; fi

      - name: Run pre-commit check
        run: |
          cd islamapp
          pip install pre-commit
          pre-commit install
          # pre-commit run --all-files
