name: CI - Linter

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
        - '*'
  pull_request:
    branches:
        - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f islamapp/requirements.txt ]; then pip install -r islamapp/requirements.txt; fi

    - name: Run pre-commit check
      run: |
        cd islamapp &&
        pre-commit run --all-files
